services:
  postgres:
    image: postgres:16
    container_name: dog_sitter_postgres
    environment:
      POSTGRES_USER: dog_sitter
      POSTGRES_PASSWORD: dog_sitter_pass
      POSTGRES_DB: dog_sitter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: