"""create initial tables

Revision ID: 1a26a881024a
Revises: 
Create Date: 2026-05-10 22:00:29.520083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a26a881024a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sitter_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dogs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('dog_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sitter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dog_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_price > 0', name='bookings_total_price_positive'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_instructions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dog_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding_status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dog_id')
    )
    op.create_table('care_instruction_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('care_instruction_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_instruction_id'], ['care_instructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='payments_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('stripe_payment_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reviewer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sitter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='reviews_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('care_instruction_chunks')
    op.drop_table('care_instructions')
    op.drop_table('bookings')
    op.drop_table('dogs')
    op.drop_table('users')
    # ### end Alembic commands ###
